FROM oven/bun:1

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package.json .

COPY prisma ./prisma

RUN bun install --production

RUN bun x prisma generate

COPY src ./src

EXPOSE 3000

CMD ["bun", "src/index.js"]